- .gitignore
- docs/data-sources/cluster.md
- docs/resources/cluster.md
- managed/data_source_cluster_name.go
- managed/models.go
- managed/resource_cluster.go
We should be able to get endpoints and certificate from the server.
> [CLOUDGA-8441] Terraform provider should expose connection endpoints

- LICENSE.md
- NOTICE.txt
- main.go
- managed/common.go
- managed/common_test.go
- managed/data_source_backup.go
- managed/data_source_cluster_name.go
- managed/models.go
- managed/provider.go
- managed/resource_allow_list.go
- managed/resource_allow_list_test.go
- managed/resource_backup.go
- managed/resource_cluster.go
- managed/resource_read_replica.go
- managed/resource_vpc.go
- managed/resource_vpc_peering.go
- managed/util.go
- managed/util_test.go
> Add licensing and proper headers

- .gitignore
- docs/data-sources/cluster.md
- docs/resources/cluster.md
- docs/resources/read_replicas.md
- go.mod
- go.sum
- managed/data_source_cluster_name.go
- managed/models.go
- managed/resource_cluster.go
- managed/resource_read_replica.go
- managed/util.go
- Terraform support for aws custom disk IOPS
- Tested cluster creation, read replica creation, cluster edit, read replica edit with custom IOPS. Validated custom IOPS was set in apiserver and in cloud provider
> [CLOUDGA-14180] Terraform support for aws custom disk IOPS

- docs/data-sources/cluster.md
- managed/data_source_cluster_name.go
Even latest version is failing .. 
Data struct was missing
> Fix Panic issues

- managed/resource_cluster.go
Edit cluster CMK was recently made into a task in apiserver, added retry logic to support that.
> [CLOUDGA-14712] Handle edit cluster cmk task

- docs/guides/import.md
- docs/resources/allow_list.md
- docs/resources/vpc.md
- examples/resources/ybm_allow_list/generated_resources.tf
- examples/resources/ybm_allow_list/import.sh
- examples/resources/ybm_allow_list/import.tf
- examples/resources/ybm_vpc/import.sh
- managed/resource_allow_list.go
- managed/resource_allow_list_test.go
- managed/resource_vpc.go
- templates/guides/import.md.tmpl
- templates/resources/allow_list.md.tmpl
- templates/resources/vpc.md.tmpl
That should fix the import for NAL and VPC
For the import I had to less trust the state file as their is no data inside, so instead I will fetch  accountId and projectId from the source
> Fix VPC and NAL import

- managed/resource_vpc.go
Fix region CIDR which the api calculate and get back to us.
A bit of cleaning
> Make region cidr as computed as well

- managed/resource_private_endpoint.go
Small fix for Private service endpoint.
> Small fix for PSE

- managed/common.go
- managed/resource_cluster.go
Increased timeout to 1 hours for edit and create operation
Used same technique  as YBM CLI to check cluster creation and edit using task
Fixes CLOUDGA-16720
Fixes CLOUDGA-16721
> Fixes for CLOUDGA-16720  CLOUDGA-16721

- docs/resources/cluster.md
- examples/resources/ybm_cluster/single-region-public-access.tf
- managed/models.go
- managed/resource_associate_me_cluster.go
- managed/resource_cluster.go
- templates/resources/cluster.md.tmpl
Adding a setting for enabling public access for a cluster.
Fixes  #75 .
> Public access setting

- docs/data-sources/cluster.md
- managed/data_source_cluster_name.go
> Added missing structure endpoints and public access

- managed/resource_cluster.go
That should solve https://yugabyte.atlassian.net/browse/CLOUDGA-19922
Use proper task checking instead of infinity loop ..
> Use proper task check for cluster deletion

- docs/resources/cluster.md
- managed/models.go
- managed/resource_cluster.go
Support setting the preferred region and default region for clusters.
> Support is_preferred and is_default

- docs/resources/integration.md
- go.mod
- go.sum
- managed/resource_integration.go
1. Removed old GCP feature flagging due to complexity and poor error handling.
2. Added a simpler, more reliable feature flag system.
1. Better Error Handling: Ensures smooth transitions when toggling the feature.
2. Easier Future Integration: Simplifies code for easier expansion.
Output when creating a GCP integration when FF is disabled:
> [CLOUDGA-24216] Simplify GCP FF

- go.mod
- go.sum
- managed/resource_cluster.go
Changed terraform cluster creation to use b64 encoded db credentials
Tested by creating a cluster and connecting using given credentials
> [CLOUDGA-23989] Use encoded db credentials

- managed/fflags/feature_flags.go
- managed/resource_cluster.go
Tested edit cluster. Added feature flag
> Edit Cluster fix for Connection Pooling

- docs/resources/associate_metrics_exporter_cluster.md
- docs/resources/cluster.md
- docs/resources/db_audit_logging.md
- docs/resources/db_query_logging.md
- docs/resources/integration.md
- managed/resource_associate_me_cluster.go
- managed/resource_cluster.go
- managed/resource_db_audit_logging.go
- managed/resource_db_query_logging.go
- managed/resource_integration.go
1. Added reference to log resources in integration resource
2. Improved doc for log resources
3. Fixed error in cluster doc
> Changes to log configuration docs

- managed/resource_pitr_clone.go
Allow clone now for DBs that have existing PITR configs as backend supports this op
> [CLOUDGA-26650] Allow clone now for DBs that have existing PITR configs

- managed/resource_pitr_clone.go
- managed/resource_pitr_config.go
- managed/resource_pitr_restore.go
Do not use ignoreChangesModifier in PITR config ops
> Do not use ignoreChangesModifier in PITR config ops

- managed/resource_pitr_clone.go
- managed/resource_pitr_config.go
- managed/resource_pitr_restore.go
> Mark PITR config ID optional

- managed/resource_pitr_clone.go
- managed/resource_pitr_config.go
- managed/resource_pitr_restore.go
Retention period must be between 2 and 14 days
> Retention period must be between 2 and 14 days

- managed/resource_pitr_clone.go
- managed/resource_pitr_config.go
> Fix PITR config resource read

- managed/resource_pitr_clone.go
- managed/resource_pitr_config.go
Add spaces to pitr config and clone error messages
> [CLOUDGA-27140] Add spaces to pitr config and clone error messages
