- go.mod
- go.sum
- managed/resource_cluster.go
Due to a regression in our REST API auto-generated golang code, the username and password were reversed when passed to the golang library.
This fixes the inconsistency.
> Fix user/password reversal

- managed/common.go
- managed/error.go
When some enum's change on the API side, then
the deserialization fails on the client side since the new fields are not known. This results in failures to use the Terraform provider.
We fix this by ignoring the class of issues that
happens during deserialization.
> Fix API interoperability

- docs/resources/vpc.md
- managed/data_source_cluster_name.go
- managed/models.go
- managed/resource_read_replica.go
- managed/resource_vpc.go
- managed/resource_vpc_peering.go
This PR provides the external VPC ID( the VPC ID in the cloud provider ) in the VPC resource. This is needed to fully automate VPC peering. 
In addition to it, the following minor bugs have been fixed:
- Check for wrong cluster name in the cluster data source
- Increase timeout during read replica creation to support the creation of a large number of read replicas at once
- TF plan always shows VPC peering resource needs to be updated inspite of no changes to the resources. This has been fixed.
> Provide external VPC ID in the VPC resource and fix minor bugs

- docs/resources/cluster.md
- examples/resources/ybm_cluster/single-region-aws-cmk.tf
- examples/resources/ybm_cluster/single-region-gcp-cmk.tf
- go.mod
- go.sum
- managed/models.go
- managed/resource_cluster.go
Summary:
This PR adds encryption at rest support to Terraform.
1. Cluster creation with AWS CMK and GCP CMK 
2. Adding EAR to existing cluster 
3. Enable or disable EAR for existing EAR enabled cluster.
Testing:
Manually tested out all the scenarios.
> Add BYOK feature support to Terraform

- docs/resources/cluster.md
- managed/resource_cluster.go
Summary:
1. Input validation when both AWS and GCP CMK spec are given as present in cmk_spec. 
2. Supported null value when universe domain is not provided in GCP CMK Spec.
Testing:
Tested manually
> Fixed input validation and universe domain null issue for CMK 

- go.mod
- go.sum
- managed/resource_user.go
Issue: https://yugabyte.atlassian.net/browse/CLOUDGA-14807
`ybm_user.example_user: Creating...
╷
│ Error: Unable to invite user 
│ 
│   with ybm_user.example_user,
│   on user.tf line 22, in resource "ybm_user" "example_user":
│   22: resource "ybm_user" "example_user" {
│ 
│ Email is in invalid format`
`ybm_user.example_user: Creating...
╷
│ Error: Unable to invite user
│ 
│   with ybm_user.example_user,
│   on user.tf line 22, in resource "ybm_user" "example_user":
│   22: resource "ybm_user" "example_user" {
│ 
│ The role provided for the user to be invited does not exist.`
`│ Error: User Email modified for existing user
│ 
│   with ybm_user.example_user,
│   on user.tf line 22, in resource "ybm_user" "example_user":
│   22: resource "ybm_user" "example_user" {
│ 
│ The email was …
> [CLOUDGA-14807] Add better error handling for user resource management

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- managed/data_source_cluster_name.go
- managed/models.go
- managed/resource_cluster.go
This adds the required changes for being able to specify the number of faults to tolerate for configuring the replication factor of the cluster.
> [CLOUDGA-15695] Add support for RF5/7

- managed/resource_cluster.go
In case the public access is not specified, the value in one of the conditions is false, leading to cluster creation failure.
> Fix public access not specified

- managed/resource_read_replica.go
This PR fixes the default multiZone value to true, is the bool value is unknown. Verified locally that multiZone was earlier defaulting to `false`, and is defaulting to `true` post this fix.
> [CLOUDGA-17071] Fix read replicas default multiZone value to true

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- examples/resources/ybm_cluster/single-region-aws-cmk.tf
- examples/resources/ybm_cluster/single-region-azure-cmk.tf
- go.mod
- go.sum
- managed/data_source_cluster_name.go
- managed/models.go
- managed/resource_backup.go
- managed/resource_cluster.go
- mock_yugabytedb_managed_go_client_internal/mock_api_account.go
Summary:
This PR adds support for Azure CMK:
1. Create a cluster with Azure CMK
2. Update state of Azure cmk
3. Enable/disable azure cmk
Additionally, also fixed a backupDescription related issue in this PR.
`
cannot use &backupDescription (value of type *string) as openapi.NullableString value in assignment
`
> [CLOUDGA-17429] Add Azure CMK support to Terraform 

- managed/resource_cluster.go
Summary:
According to a recent change, YBM should only mask client secret. This PR unmasks client id and tenant id.
> Unmask client id and tenant id in azure cmk spec 

- managed/resource_allow_list.go
When updating allowlist we will first detach from cluster then create the new one and reattach if necessary to the cluster (if the cluster is managed within terraform using link like 
```
cluster_allow_list_ids = [ybm_allow_list.example_allow_list.allow_list_id]
```
> Support recreating alllowlist

- go.mod
- go.sum
- managed/resource_associate_db_audit_export_config_cluster.go
Added support for update and delete db audit log config resource 
Manually simulated `Create`, `Read`, `Update`, `Delete` funcs for the respective resource. Working as expected
> Added support for update and delete db audit log config resource

- .github/workflows/release.yml
The `--rm-dist` flag has been deprecated and is replaced with `--clean`
> Fix go-releaser

- go.mod
- go.sum
- managed/resource_read_replica.go
[CLOUDGA-24039](https://yugabyte.atlassian.net/browse/CLOUDGA-24039) : Fixed delete read-replica error message.
> [CLOUDGA-24039] Fixed delete read-replica error message.

- managed/models.go
- managed/resource_db_query_logging.go
- Added support for db query logging update & delete resource.
- Remove required field `cluster_name`.
- Added `cluster_id` as required field for consistency with other resources.
```terraform
resource "ybm_database_query_logging" "dql_by" {
cluster_id = "c2e9c74a-cbea-4ee9-95d1-1537bc85b4be"
integration_name = "nuij"
log_config = {
log_min_duration_statement = 30,
debug_print_plan = false,
log_connections = true,
log_disconnections = true,
log_duration = true,
log_error_verbosity = "DEFAULT",
log_statement = "NONE",
log_min_error_statement = "ERROR",
log_line_prefix = "%m :%r :%u @ %d :[%p] : %a :"
}
}
```
> Added support for db query logging update & delete resource

- managed/provider.go
CLOUDGA-23240 change resource name for ybm_database_query_logging to ybm_db_query_logging.
This is to make it consistent with CLI and audit logs resource name `ybm_db_audit_logging`.
> CLOUDGA-23240 change resource name for ybm_database_query_logging

- docs/resources/integration.md
- managed/models.go
- managed/resource_integration.go
```terraform
resource "ybm_integration" "prometheus" {
config_name = "prometheus-example"
type        = "PROMETHEUS"
prometheus_spec = {
endpoint = "http://yourcompany.com/api/v1/otlp"
}
}
```
```shell
> tfp
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "ybm_integration" "prometheus" {
+ account_id      = (known after apply)
+ config_id       = (known after apply)
+ config_name     = "prometheus-example"
+ is_valid        = (known after apply)
+ project_id      = (known after apply)
+ prometheus_spec = {
+ endpoint = "http://yourcompany.com/api/v1/otlp"
}
+ type            = "PROMETHEUS"
}
Plan: 1 to add, 0 to change, 0 to destroy. …
```
> [CLOUDGA-22303] Add support for integration type PROMETHEUS

- docs/data-sources/integration.md
- docs/resources/integration.md
- managed/data_source_integration.go
- managed/models.go
- managed/resource_integration.go
- Add support for integration type VICTORIAMETRICS.
- Add TF `data-source` support for both Prometheus & VictoriaMetrics.
```terraform
resource "ybm_integration" "victoriametrics" {
config_name = "victoriametrics-example"
type        = "VICTORIAMETRICS"
victoriametrics_spec = {
endpoint = "http://yourcompany.com/"
}
}
```
```shell
> tfp
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "ybm_integration" "victoriametrics" {
+ account_id           = (known after apply)
+ config_id            = (known after apply)
+ config_name          = "victoriametrics-example"
+ is_valid             = (known after apply)
+ project_id           = (known …
```
> [CLOUDGA-24745] Add support for integration type VICTORIAMETRICS

- managed/resource_db_audit_logging.go
When updating the DB audit logging resource, the integration data was not being fetched correctly. As a result, the value was null in the request payload, leading to an error during the update process.
This PR addresses the issue by ensuring that the appropriate integration data is fetched
> [CLOUDGA-24855] Fix update DB Audit logging error 

- managed/plan_modifier/plan_modifier.go
- managed/resource_integration.go
Show error during TF plan for immutable field change. For more details, refer [here](https://yugabyte.atlassian.net/browse/CLOUDGA-24889).
- Currently if a resource does not support `update` operation, in `tf plan` step we generate the plan but throw error during `tf apply`. Ideally, the error should be throwing during the plan itself
- This change uses Terraforms [plan modifiers](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification) and runs method `Modify` for each attribute to which the `ImmutableFieldModifier` plan modifier is associated, which checks if a field has changed i.e. diff between current value and the value stored in state. If the value differs, it will add an error to response diagnostic.
```shell
$ terraform plan
ybm_integration.datadog: …
```
> [CLOUDGA-24889] Show error during TF plan for immutable field change

- managed/resource_api_key.go
Fixes: CLOUDGA-25821
Return as soon as we discover wrong unit is provided for API key duration.
> [CLOUDGA-25821] Stop API key creation if wrong unit provided

- managed/resource_cluster.go
Today, when we run `terraform plan` we show all the computed attributed though they didn't change. It makes it difficult to properly identify the attributes that didn't change. Plan modifiers come to our rescue here helping us hide the computed attributes from the plan.
For example, here is the plan after changing `num_cores` before the change was done:
```
bash-5.2$ terraform plan
ybm_allow_list.mylist: Refreshing state...
ybm_cluster.single_region: Refreshing state...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "ybm_cluster" "single_region" {
~ account_id             = "5379da8e-9248-42f4-bd25-ebd7341eae69" -> (known …
```
> Add plan modifiers to stop showing values that didn't change on TF plan

- go.mod
- go.sum
- managed/common.go
Tested by trying to create a cluster(with incorrect fields intentionally) that calls the get supported nodes API.
```terraform
variable "password" {
type        = string
description = "YSQL and YCQL Password."
sensitive   = true
}
resource "ybm_cluster" "single_region_cluster" {
cluster_name = "single-region-cluster"
cloud_type   = "GCP"
cluster_type = "SYNCHRONOUS"
cluster_region_info = [
{
region    = "us-west1"
num_nodes = 1
}
]
cluster_tier           = "FREE"
fault_tolerance        = "ZONE" # this value shd be none for free tier. Set to zone intentionally
node_config = {
num_cores    = 2
disk_size_gb = 50
}
credentials = {
username = "example_user"
password = var.password
}
}
```
And in proxy, I could see the call:
> [CLOUDGA-26188] Use new API's get instance-types, cloud-regions & node configs

- docs/resources/allow_list.md
- managed/resource_allow_list.go
Allow list description is optional in UI and API, inconsistent with TF
> Changed allowlist description to optional

- docs/data-sources/cluster.md
- docs/resources/cluster.md
- examples/resources/ybm_cluster/cluster-edit-backup-replication.tf
- go.mod
- go.sum
- managed/data_source_cluster_name.go
- managed/fflags/feature_flags.go
- managed/models.go
- managed/resource_cluster.go
- mock_yugabytedb_managed_go_client_internal/mock_api_account.go
- templates/resources/cluster.md.tmpl
1. GCP Backup Replication Target Update via Edit Cluster
- Users can now update the `backup_replication_gcp_target` for GCP clusters through the Edit workflow. This enables flexible backup strategies for both SYNCHRONOUS and GEO_PARTITIONED clusters, with validation for cluster type, tier, and cloud provider.
2. Cluster Data Source Schema Fixes
- Added missing fields to the data source schema:
- `desired_connection_pooling_state`
- `is_preferred`
- `is_default`
- This resolves errors when fetching cluster data and ensures the Terraform state is populated correctly.
3. Backup Region Visibility
- Introduced the `backup_region` field to cluster region info, making it easy to identify which regions are designated as backup regions.
> [CLOUDGA-28235] Update edit cluster schema and operation to allow backup replication related modifications

- managed/resource_cluster.go
- managed/resource_read_replica.go
Get cluster region without using the `readOnly` parameter. Determine the difference between cluster data source and resource based on the region index map.
> Fix error with read multi-region cluster

- managed/resource_cluster.go
[CLOUDGA-29417](https://yugabyte.atlassian.net/browse/CLOUDGA-29417) : Use node count to deduce cluster state polling timeout during edits.
> [CLOUDGA-29417] Use node count to deduce cluster state polling timeout during edits.

- .goreleaser.yml
[CLOUDGA-29573](https://yugabyte.atlassian.net/browse/CLOUDGA-29573) : Removed usage of deprecated 'archives.format' in Go Releaser.
Ref : https://goreleaser.com/deprecations/#archivesformat
> [CLOUDGA-29573] Removed usage of deprecated 'archives.format' in Go Releaser.
